/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SSCAPIJNI */

#ifndef _Included_SSCAPIJNI
#define _Included_SSCAPIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SSCAPIJNI
 * Method:    ssc_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1version
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_build_info
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1build_1info
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_INVALID_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1INVALID_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_STRING_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1STRING_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_NUMBER_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1NUMBER_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_ARRAY_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1ARRAY_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_MATRIX_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1MATRIX_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_TABLE_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1TABLE_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_SSCAPIJNI_ssc_1data_1create
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_unassign
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1unassign
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_query
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1data_1query
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_first
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1data_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_next
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1data_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_set_string
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1set_1string
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_set_number
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1set_1number
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_set_array
 * Signature: (JLjava/lang/String;[DI)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1set_1array
  (JNIEnv *, jclass, jlong, jstring, jdoubleArray, jint);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_set_matrix
 * Signature: (JLjava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1set_1matrix
  (JNIEnv *, jclass, jlong, jstring, jdoubleArray, jint, jint);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_set_table
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1data_1set_1table
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_get_string
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1data_1get_1string
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_get_number
 * Signature: (JLjava/lang/String;[D)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1data_1get_1number
  (JNIEnv *, jclass, jlong, jstring, jdoubleArray);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_get_array
 * Signature: (JLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_SSCAPIJNI_ssc_1data_1get_1array
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_get_matrix
 * Signature: (JLjava/lang/String;[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_SSCAPIJNI_ssc_1data_1get_1matrix
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_data_get_table
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_SSCAPIJNI_ssc_1data_1get_1table
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_entry
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_SSCAPIJNI_ssc_1module_1entry
  (JNIEnv *, jclass, jint);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_entry_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1entry_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_entry_description
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1entry_1description
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_entry_version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1entry_1version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_SSCAPIJNI_ssc_1module_1create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1module_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_INPUT_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1INPUT_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_OUTPUT_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1OUTPUT_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_INOUT_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1INOUT_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_var_info
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_SSCAPIJNI_ssc_1module_1var_1info
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_var_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1info_1var_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_data_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1info_1data_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_label
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1label
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_units
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1units
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_meta
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1meta
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_group
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_required
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1required
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_constraints
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1constraints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_info_uihint
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1info_1uihint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_exec_simple
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1module_1exec_1simple
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_exec_simple_nothread
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1module_1exec_1simple_1nothread
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_LOG_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1LOG_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_UPDATE_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1UPDATE_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_EXECUTE_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1EXECUTE_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_exec
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1module_1exec
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_exec_with_handler
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_ssc_1module_1exec_1with_1handler
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_exec_set_print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1module_1exec_1set_1print
  (JNIEnv *, jclass, jint);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_extproc_output
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI_ssc_1module_1extproc_1output
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_NOTICE_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1NOTICE_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_WARNING_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1WARNING_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    SSC_ERROR_get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SSCAPIJNI_SSC_1ERROR_1get
  (JNIEnv *, jclass);

/*
 * Class:     SSCAPIJNI
 * Method:    ssc_module_log
 * Signature: (JI[I[F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SSCAPIJNI_ssc_1module_1log
  (JNIEnv *, jclass, jlong, jint, jintArray, jfloatArray);

/*
 * Class:     SSCAPIJNI
 * Method:    __ssc_segfault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SSCAPIJNI__1_1ssc_1segfault
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
